// source: protos/movies_v1/movies_v1.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.movies_v1.AddMoviesRequest', null, global);
goog.exportSymbol('proto.movies_v1.AddMoviesResponse', null, global);
goog.exportSymbol('proto.movies_v1.Countries', null, global);
goog.exportSymbol('proto.movies_v1.DeleteMoviesRequest', null, global);
goog.exportSymbol('proto.movies_v1.DeleteMoviesResponse', null, global);
goog.exportSymbol('proto.movies_v1.Genres', null, global);
goog.exportSymbol('proto.movies_v1.GetMovieItem', null, global);
goog.exportSymbol('proto.movies_v1.GetMoviesByFilterItem', null, global);
goog.exportSymbol('proto.movies_v1.GetMoviesByFilterRequest', null, global);
goog.exportSymbol('proto.movies_v1.GetMoviesByIdRequest', null, global);
goog.exportSymbol('proto.movies_v1.GetMoviesByIdResponse', null, global);
goog.exportSymbol('proto.movies_v1.GetMoviesRequest', null, global);
goog.exportSymbol('proto.movies_v1.GetMoviesResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMoviesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.GetMoviesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMoviesRequest.displayName = 'proto.movies_v1.GetMoviesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMoviesByIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.GetMoviesByIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMoviesByIdRequest.displayName = 'proto.movies_v1.GetMoviesByIdRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMoviesByFilterRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.GetMoviesByFilterRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMoviesByFilterRequest.displayName = 'proto.movies_v1.GetMoviesByFilterRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMoviesByFilterItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.movies_v1.GetMoviesByFilterItem.repeatedFields_, null);
};
goog.inherits(proto.movies_v1.GetMoviesByFilterItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMoviesByFilterItem.displayName = 'proto.movies_v1.GetMoviesByFilterItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.AddMoviesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.movies_v1.AddMoviesRequest.repeatedFields_, null);
};
goog.inherits(proto.movies_v1.AddMoviesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.AddMoviesRequest.displayName = 'proto.movies_v1.AddMoviesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.Countries = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.Countries, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.Countries.displayName = 'proto.movies_v1.Countries';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.Genres = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.Genres, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.Genres.displayName = 'proto.movies_v1.Genres';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.DeleteMoviesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.DeleteMoviesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.DeleteMoviesRequest.displayName = 'proto.movies_v1.DeleteMoviesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMoviesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.movies_v1.GetMoviesResponse.repeatedFields_, null);
};
goog.inherits(proto.movies_v1.GetMoviesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMoviesResponse.displayName = 'proto.movies_v1.GetMoviesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMovieItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.GetMovieItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMovieItem.displayName = 'proto.movies_v1.GetMovieItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.GetMoviesByIdResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.GetMoviesByIdResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.GetMoviesByIdResponse.displayName = 'proto.movies_v1.GetMoviesByIdResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.AddMoviesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.AddMoviesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.AddMoviesResponse.displayName = 'proto.movies_v1.AddMoviesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.movies_v1.DeleteMoviesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.movies_v1.DeleteMoviesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.movies_v1.DeleteMoviesResponse.displayName = 'proto.movies_v1.DeleteMoviesResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMoviesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMoviesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMoviesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    limit: jspb.Message.getFieldWithDefault(msg, 1, 0),
    page: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMoviesRequest}
 */
proto.movies_v1.GetMoviesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMoviesRequest;
  return proto.movies_v1.GetMoviesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMoviesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMoviesRequest}
 */
proto.movies_v1.GetMoviesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLimit(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMoviesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMoviesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMoviesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 limit = 1;
 * @return {number}
 */
proto.movies_v1.GetMoviesRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesRequest} returns this
 */
proto.movies_v1.GetMoviesRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 page = 2;
 * @return {number}
 */
proto.movies_v1.GetMoviesRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesRequest} returns this
 */
proto.movies_v1.GetMoviesRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMoviesByIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMoviesByIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMoviesByIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMoviesByIdRequest}
 */
proto.movies_v1.GetMoviesByIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMoviesByIdRequest;
  return proto.movies_v1.GetMoviesByIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMoviesByIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMoviesByIdRequest}
 */
proto.movies_v1.GetMoviesByIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMoviesByIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMoviesByIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMoviesByIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdRequest} returns this
 */
proto.movies_v1.GetMoviesByIdRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMoviesByFilterRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMoviesByFilterRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByFilterRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filters: (f = msg.getFilters()) && proto.movies_v1.GetMoviesByFilterItem.toObject(includeInstance, f),
    limit: jspb.Message.getFieldWithDefault(msg, 2, 0),
    page: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMoviesByFilterRequest}
 */
proto.movies_v1.GetMoviesByFilterRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMoviesByFilterRequest;
  return proto.movies_v1.GetMoviesByFilterRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMoviesByFilterRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMoviesByFilterRequest}
 */
proto.movies_v1.GetMoviesByFilterRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.movies_v1.GetMoviesByFilterItem;
      reader.readMessage(value,proto.movies_v1.GetMoviesByFilterItem.deserializeBinaryFromReader);
      msg.setFilters(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLimit(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMoviesByFilterRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMoviesByFilterRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByFilterRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilters();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.movies_v1.GetMoviesByFilterItem.serializeBinaryToWriter
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional GetMoviesByFilterItem filters = 1;
 * @return {?proto.movies_v1.GetMoviesByFilterItem}
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.getFilters = function() {
  return /** @type{?proto.movies_v1.GetMoviesByFilterItem} */ (
    jspb.Message.getWrapperField(this, proto.movies_v1.GetMoviesByFilterItem, 1));
};


/**
 * @param {?proto.movies_v1.GetMoviesByFilterItem|undefined} value
 * @return {!proto.movies_v1.GetMoviesByFilterRequest} returns this
*/
proto.movies_v1.GetMoviesByFilterRequest.prototype.setFilters = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.movies_v1.GetMoviesByFilterRequest} returns this
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.clearFilters = function() {
  return this.setFilters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.hasFilters = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 limit = 2;
 * @return {number}
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByFilterRequest} returns this
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 page = 3;
 * @return {number}
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByFilterRequest} returns this
 */
proto.movies_v1.GetMoviesByFilterRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.movies_v1.GetMoviesByFilterItem.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMoviesByFilterItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMoviesByFilterItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByFilterItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    typemovie: jspb.Message.getFieldWithDefault(msg, 1, 0),
    search: jspb.Message.getFieldWithDefault(msg, 2, ""),
    genresList: jspb.Message.toObjectList(msg.getGenresList(),
    proto.movies_v1.Genres.toObject, includeInstance),
    yearmin: jspb.Message.getFieldWithDefault(msg, 4, 0),
    yearmax: jspb.Message.getFieldWithDefault(msg, 5, 0),
    bestmovie: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMoviesByFilterItem}
 */
proto.movies_v1.GetMoviesByFilterItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMoviesByFilterItem;
  return proto.movies_v1.GetMoviesByFilterItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMoviesByFilterItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMoviesByFilterItem}
 */
proto.movies_v1.GetMoviesByFilterItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTypemovie(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearch(value);
      break;
    case 3:
      var value = new proto.movies_v1.Genres;
      reader.readMessage(value,proto.movies_v1.Genres.deserializeBinaryFromReader);
      msg.addGenres(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setYearmin(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setYearmax(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBestmovie(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMoviesByFilterItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMoviesByFilterItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByFilterItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypemovie();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSearch();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGenresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.movies_v1.Genres.serializeBinaryToWriter
    );
  }
  f = message.getYearmin();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getYearmax();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getBestmovie();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional int32 typeMovie = 1;
 * @return {number}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.getTypemovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.setTypemovie = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string search = 2;
 * @return {string}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.getSearch = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.setSearch = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Genres genres = 3;
 * @return {!Array<!proto.movies_v1.Genres>}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.getGenresList = function() {
  return /** @type{!Array<!proto.movies_v1.Genres>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.movies_v1.Genres, 3));
};


/**
 * @param {!Array<!proto.movies_v1.Genres>} value
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
*/
proto.movies_v1.GetMoviesByFilterItem.prototype.setGenresList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.movies_v1.Genres=} opt_value
 * @param {number=} opt_index
 * @return {!proto.movies_v1.Genres}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.addGenres = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.movies_v1.Genres, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.clearGenresList = function() {
  return this.setGenresList([]);
};


/**
 * optional int32 yearMin = 4;
 * @return {number}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.getYearmin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.setYearmin = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 yearMax = 5;
 * @return {number}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.getYearmax = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.setYearmax = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool bestMovie = 6;
 * @return {boolean}
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.getBestmovie = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.movies_v1.GetMoviesByFilterItem} returns this
 */
proto.movies_v1.GetMoviesByFilterItem.prototype.setBestmovie = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.movies_v1.AddMoviesRequest.repeatedFields_ = [3,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.AddMoviesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.AddMoviesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.AddMoviesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.AddMoviesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    countriesList: jspb.Message.toObjectList(msg.getCountriesList(),
    proto.movies_v1.Countries.toObject, includeInstance),
    releasedate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timemovie: jspb.Message.getFieldWithDefault(msg, 5, 0),
    scorekp: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    scoreimdb: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    poster: jspb.Message.getFieldWithDefault(msg, 8, ""),
    typemovie: jspb.Message.getFieldWithDefault(msg, 9, 0),
    genresList: jspb.Message.toObjectList(msg.getGenresList(),
    proto.movies_v1.Genres.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.AddMoviesRequest}
 */
proto.movies_v1.AddMoviesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.AddMoviesRequest;
  return proto.movies_v1.AddMoviesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.AddMoviesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.AddMoviesRequest}
 */
proto.movies_v1.AddMoviesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = new proto.movies_v1.Countries;
      reader.readMessage(value,proto.movies_v1.Countries.deserializeBinaryFromReader);
      msg.addCountries(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReleasedate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimemovie(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScorekp(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScoreimdb(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPoster(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTypemovie(value);
      break;
    case 10:
      var value = new proto.movies_v1.Genres;
      reader.readMessage(value,proto.movies_v1.Genres.deserializeBinaryFromReader);
      msg.addGenres(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.AddMoviesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.AddMoviesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.AddMoviesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.AddMoviesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCountriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.movies_v1.Countries.serializeBinaryToWriter
    );
  }
  f = message.getReleasedate();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getTimemovie();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getScorekp();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getScoreimdb();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getPoster();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getTypemovie();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getGenresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.movies_v1.Genres.serializeBinaryToWriter
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.movies_v1.AddMoviesRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.movies_v1.AddMoviesRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Countries countries = 3;
 * @return {!Array<!proto.movies_v1.Countries>}
 */
proto.movies_v1.AddMoviesRequest.prototype.getCountriesList = function() {
  return /** @type{!Array<!proto.movies_v1.Countries>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.movies_v1.Countries, 3));
};


/**
 * @param {!Array<!proto.movies_v1.Countries>} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
*/
proto.movies_v1.AddMoviesRequest.prototype.setCountriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.movies_v1.Countries=} opt_value
 * @param {number=} opt_index
 * @return {!proto.movies_v1.Countries}
 */
proto.movies_v1.AddMoviesRequest.prototype.addCountries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.movies_v1.Countries, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.clearCountriesList = function() {
  return this.setCountriesList([]);
};


/**
 * optional int32 releaseDate = 4;
 * @return {number}
 */
proto.movies_v1.AddMoviesRequest.prototype.getReleasedate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setReleasedate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 timeMovie = 5;
 * @return {number}
 */
proto.movies_v1.AddMoviesRequest.prototype.getTimemovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setTimemovie = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double scoreKP = 6;
 * @return {number}
 */
proto.movies_v1.AddMoviesRequest.prototype.getScorekp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setScorekp = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double scoreIMDB = 7;
 * @return {number}
 */
proto.movies_v1.AddMoviesRequest.prototype.getScoreimdb = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setScoreimdb = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional string poster = 8;
 * @return {string}
 */
proto.movies_v1.AddMoviesRequest.prototype.getPoster = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setPoster = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int32 typeMovie = 9;
 * @return {number}
 */
proto.movies_v1.AddMoviesRequest.prototype.getTypemovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.setTypemovie = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * repeated Genres genres = 10;
 * @return {!Array<!proto.movies_v1.Genres>}
 */
proto.movies_v1.AddMoviesRequest.prototype.getGenresList = function() {
  return /** @type{!Array<!proto.movies_v1.Genres>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.movies_v1.Genres, 10));
};


/**
 * @param {!Array<!proto.movies_v1.Genres>} value
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
*/
proto.movies_v1.AddMoviesRequest.prototype.setGenresList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.movies_v1.Genres=} opt_value
 * @param {number=} opt_index
 * @return {!proto.movies_v1.Genres}
 */
proto.movies_v1.AddMoviesRequest.prototype.addGenres = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.movies_v1.Genres, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.movies_v1.AddMoviesRequest} returns this
 */
proto.movies_v1.AddMoviesRequest.prototype.clearGenresList = function() {
  return this.setGenresList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.Countries.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.Countries.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.Countries} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.Countries.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.Countries}
 */
proto.movies_v1.Countries.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.Countries;
  return proto.movies_v1.Countries.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.Countries} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.Countries}
 */
proto.movies_v1.Countries.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.Countries.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.Countries.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.Countries} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.Countries.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.movies_v1.Countries.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.Countries} returns this
 */
proto.movies_v1.Countries.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.Genres.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.Genres.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.Genres} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.Genres.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.Genres}
 */
proto.movies_v1.Genres.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.Genres;
  return proto.movies_v1.Genres.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.Genres} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.Genres}
 */
proto.movies_v1.Genres.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.Genres.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.Genres.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.Genres} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.Genres.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.movies_v1.Genres.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.Genres} returns this
 */
proto.movies_v1.Genres.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.DeleteMoviesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.DeleteMoviesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.DeleteMoviesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.DeleteMoviesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.DeleteMoviesRequest}
 */
proto.movies_v1.DeleteMoviesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.DeleteMoviesRequest;
  return proto.movies_v1.DeleteMoviesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.DeleteMoviesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.DeleteMoviesRequest}
 */
proto.movies_v1.DeleteMoviesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.DeleteMoviesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.DeleteMoviesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.DeleteMoviesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.DeleteMoviesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.movies_v1.DeleteMoviesRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.DeleteMoviesRequest} returns this
 */
proto.movies_v1.DeleteMoviesRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.movies_v1.GetMoviesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMoviesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMoviesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMoviesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    moviesList: jspb.Message.toObjectList(msg.getMoviesList(),
    proto.movies_v1.GetMovieItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMoviesResponse}
 */
proto.movies_v1.GetMoviesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMoviesResponse;
  return proto.movies_v1.GetMoviesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMoviesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMoviesResponse}
 */
proto.movies_v1.GetMoviesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.movies_v1.GetMovieItem;
      reader.readMessage(value,proto.movies_v1.GetMovieItem.deserializeBinaryFromReader);
      msg.addMovies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMoviesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMoviesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMoviesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMoviesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.movies_v1.GetMovieItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated GetMovieItem movies = 1;
 * @return {!Array<!proto.movies_v1.GetMovieItem>}
 */
proto.movies_v1.GetMoviesResponse.prototype.getMoviesList = function() {
  return /** @type{!Array<!proto.movies_v1.GetMovieItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.movies_v1.GetMovieItem, 1));
};


/**
 * @param {!Array<!proto.movies_v1.GetMovieItem>} value
 * @return {!proto.movies_v1.GetMoviesResponse} returns this
*/
proto.movies_v1.GetMoviesResponse.prototype.setMoviesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.movies_v1.GetMovieItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.movies_v1.GetMovieItem}
 */
proto.movies_v1.GetMoviesResponse.prototype.addMovies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.movies_v1.GetMovieItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.movies_v1.GetMoviesResponse} returns this
 */
proto.movies_v1.GetMoviesResponse.prototype.clearMoviesList = function() {
  return this.setMoviesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMovieItem.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMovieItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMovieItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMovieItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    releasedate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    scorekp: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    scoreimdb: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    poster: jspb.Message.getFieldWithDefault(msg, 7, ""),
    typemovie: jspb.Message.getFieldWithDefault(msg, 8, 0),
    genres: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMovieItem}
 */
proto.movies_v1.GetMovieItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMovieItem;
  return proto.movies_v1.GetMovieItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMovieItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMovieItem}
 */
proto.movies_v1.GetMovieItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReleasedate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScorekp(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScoreimdb(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPoster(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTypemovie(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setGenres(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMovieItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMovieItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMovieItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMovieItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReleasedate();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getScorekp();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getScoreimdb();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getPoster();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTypemovie();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getGenres();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.movies_v1.GetMovieItem.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.movies_v1.GetMovieItem.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.movies_v1.GetMovieItem.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 releaseDate = 4;
 * @return {number}
 */
proto.movies_v1.GetMovieItem.prototype.getReleasedate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setReleasedate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional double scoreKP = 5;
 * @return {number}
 */
proto.movies_v1.GetMovieItem.prototype.getScorekp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setScorekp = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double scoreIMDB = 6;
 * @return {number}
 */
proto.movies_v1.GetMovieItem.prototype.getScoreimdb = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setScoreimdb = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string poster = 7;
 * @return {string}
 */
proto.movies_v1.GetMovieItem.prototype.getPoster = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setPoster = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 typeMovie = 8;
 * @return {number}
 */
proto.movies_v1.GetMovieItem.prototype.getTypemovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setTypemovie = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string genres = 9;
 * @return {string}
 */
proto.movies_v1.GetMovieItem.prototype.getGenres = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMovieItem} returns this
 */
proto.movies_v1.GetMovieItem.prototype.setGenres = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.GetMoviesByIdResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.GetMoviesByIdResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByIdResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    country: jspb.Message.getFieldWithDefault(msg, 4, ""),
    releasedate: jspb.Message.getFieldWithDefault(msg, 5, 0),
    timemovie: jspb.Message.getFieldWithDefault(msg, 6, 0),
    scorekp: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    scoreimdb: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    poster: jspb.Message.getFieldWithDefault(msg, 9, ""),
    typemovie: jspb.Message.getFieldWithDefault(msg, 10, 0),
    genres: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.GetMoviesByIdResponse}
 */
proto.movies_v1.GetMoviesByIdResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.GetMoviesByIdResponse;
  return proto.movies_v1.GetMoviesByIdResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.GetMoviesByIdResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.GetMoviesByIdResponse}
 */
proto.movies_v1.GetMoviesByIdResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReleasedate(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimemovie(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScorekp(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScoreimdb(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPoster(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTypemovie(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setGenres(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.GetMoviesByIdResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.GetMoviesByIdResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.GetMoviesByIdResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getReleasedate();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getTimemovie();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getScorekp();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getScoreimdb();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getPoster();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getTypemovie();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getGenres();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string country = 4;
 * @return {string}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 releaseDate = 5;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getReleasedate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setReleasedate = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 timeMovie = 6;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getTimemovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setTimemovie = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional double scoreKP = 7;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getScorekp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setScorekp = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double scoreIMDB = 8;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getScoreimdb = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setScoreimdb = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional string poster = 9;
 * @return {string}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getPoster = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setPoster = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 typeMovie = 10;
 * @return {number}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getTypemovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setTypemovie = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string genres = 11;
 * @return {string}
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.getGenres = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.GetMoviesByIdResponse} returns this
 */
proto.movies_v1.GetMoviesByIdResponse.prototype.setGenres = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.AddMoviesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.AddMoviesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.AddMoviesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.AddMoviesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    err: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.AddMoviesResponse}
 */
proto.movies_v1.AddMoviesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.AddMoviesResponse;
  return proto.movies_v1.AddMoviesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.AddMoviesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.AddMoviesResponse}
 */
proto.movies_v1.AddMoviesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.AddMoviesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.AddMoviesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.AddMoviesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.AddMoviesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getErr();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.movies_v1.AddMoviesResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.movies_v1.AddMoviesResponse} returns this
 */
proto.movies_v1.AddMoviesResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string err = 2;
 * @return {string}
 */
proto.movies_v1.AddMoviesResponse.prototype.getErr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.AddMoviesResponse} returns this
 */
proto.movies_v1.AddMoviesResponse.prototype.setErr = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.movies_v1.DeleteMoviesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.movies_v1.DeleteMoviesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.movies_v1.DeleteMoviesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.DeleteMoviesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    err: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.movies_v1.DeleteMoviesResponse}
 */
proto.movies_v1.DeleteMoviesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.movies_v1.DeleteMoviesResponse;
  return proto.movies_v1.DeleteMoviesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.movies_v1.DeleteMoviesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.movies_v1.DeleteMoviesResponse}
 */
proto.movies_v1.DeleteMoviesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.movies_v1.DeleteMoviesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.movies_v1.DeleteMoviesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.movies_v1.DeleteMoviesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.movies_v1.DeleteMoviesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErr();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string err = 1;
 * @return {string}
 */
proto.movies_v1.DeleteMoviesResponse.prototype.getErr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.movies_v1.DeleteMoviesResponse} returns this
 */
proto.movies_v1.DeleteMoviesResponse.prototype.setErr = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.movies_v1);
