version: '3.8'

services:
  kinogo:
    container_name: kinogo
    build:
      context: .
      target: dev
      network: host
    volumes:
      - ./:/app
      - ./media:/app/media
    extra_hosts:
      - "postgres:192.168.1.1"
    ports:
      - "4000:4000"

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    volumes:
        - ./internal/config/redis/:/usr/local/etc/redis
    ports:
      - "6379:6379"
      - "8001:8001"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./internal/config/grafana/:/var/lib/grafana
    extra_hosts:
      - "postgres:192.168.1.1"
    ports:
     - '3000:3000'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./internal/config/prometheus/:/etc/prometheus/
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./logs/:/var/log
    command: -config.file=/etc/promtail/config.yml

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:RalphDeadwave562208@91.215.21.236:5432/kinogo_db?sslmode=disable"
    links:
      - prometheus