version: '3.8'

services:
  kinogo:
    container_name: kinogo
    build:
      context: .
      target: dev
      network: host
    volumes:
      - ./:/app
      - ./media:/app/media
    extra_hosts:
      - "postgres:192.168.1.1"
    ports:
      - "4000:4000"
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    volumes:
        - /opt/docker/redis/etc:/usr/local/etc/redis
    ports:
      - "6379:6379"
      - "8001:8001"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
