version: '3.8'

services:
  kinogo:
    container_name: kinogo
    build:
      context: .
      target: dev
      network: host
    volumes:
      - ./:/app
      - ./media:/app/media
    extra_hosts:
      - "postgres:192.168.1.1"
    ports:
      - "80:4000"
