/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.3
 * source: protos/interactions_v1/interactions_v1.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace interactions_v1 {
    export class InteractionsRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            id?: number;
        }): InteractionsRequest {
            const message = new InteractionsRequest({});
            if (data.id != null) {
                message.id = data.id;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): InteractionsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new InteractionsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): InteractionsRequest {
            return InteractionsRequest.deserialize(bytes);
        }
    }
    export class InteractionsResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            err?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("err" in data && data.err != undefined) {
                    this.err = data.err;
                }
            }
        }
        get err() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set err(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            err?: string;
        }): InteractionsResponse {
            const message = new InteractionsResponse({});
            if (data.err != null) {
                message.err = data.err;
            }
            return message;
        }
        toObject() {
            const data: {
                err?: string;
            } = {};
            if (this.err != null) {
                data.err = this.err;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.err.length)
                writer.writeString(1, this.err);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): InteractionsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new InteractionsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.err = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): InteractionsResponse {
            return InteractionsResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedMoviesV1Service {
        static definition = {
            IncrementView: {
                path: "/interactions_v1.MoviesV1/IncrementView",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            IncrementLike: {
                path: "/interactions_v1.MoviesV1/IncrementLike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            IncrementDislike: {
                path: "/interactions_v1.MoviesV1/IncrementDislike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            DecrementView: {
                path: "/interactions_v1.MoviesV1/DecrementView",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            DecrementLike: {
                path: "/interactions_v1.MoviesV1/DecrementLike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            DecrementDislike: {
                path: "/interactions_v1.MoviesV1/DecrementDislike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract IncrementView(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract IncrementLike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract IncrementDislike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract DecrementView(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract DecrementLike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract DecrementDislike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
    }
    export class MoviesV1Client extends grpc_1.makeGenericClientConstructor(UnimplementedMoviesV1Service.definition, "MoviesV1", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        IncrementView: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.IncrementView(message, metadata, options, callback);
        };
        IncrementLike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.IncrementLike(message, metadata, options, callback);
        };
        IncrementDislike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.IncrementDislike(message, metadata, options, callback);
        };
        DecrementView: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.DecrementView(message, metadata, options, callback);
        };
        DecrementLike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.DecrementLike(message, metadata, options, callback);
        };
        DecrementDislike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.DecrementDislike(message, metadata, options, callback);
        };
    }
    export abstract class UnimplementedCommentsV1Service {
        static definition = {
            IncrementLike: {
                path: "/interactions_v1.CommentsV1/IncrementLike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            IncrementDislike: {
                path: "/interactions_v1.CommentsV1/IncrementDislike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            DecrementLike: {
                path: "/interactions_v1.CommentsV1/DecrementLike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            },
            DecrementDislike: {
                path: "/interactions_v1.CommentsV1/DecrementDislike",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: InteractionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => InteractionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: InteractionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => InteractionsResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract IncrementLike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract IncrementDislike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract DecrementLike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
        abstract DecrementDislike(call: grpc_1.ServerUnaryCall<InteractionsRequest, InteractionsResponse>, callback: grpc_1.sendUnaryData<InteractionsResponse>): void;
    }
    export class CommentsV1Client extends grpc_1.makeGenericClientConstructor(UnimplementedCommentsV1Service.definition, "CommentsV1", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        IncrementLike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.IncrementLike(message, metadata, options, callback);
        };
        IncrementDislike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.IncrementDislike(message, metadata, options, callback);
        };
        DecrementLike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.DecrementLike(message, metadata, options, callback);
        };
        DecrementDislike: GrpcUnaryServiceInterface<InteractionsRequest, InteractionsResponse> = (message: InteractionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<InteractionsResponse>, callback?: grpc_1.requestCallback<InteractionsResponse>): grpc_1.ClientUnaryCall => {
            return super.DecrementDislike(message, metadata, options, callback);
        };
    }
}
