// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: protos/metrics_v1/metrics_v1.proto

package metrics_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_NEW_USERS             MetricType = 0
	MetricType_AVG_TIME_ON_SITE      MetricType = 1
	MetricType_PAGE_VIEWS            MetricType = 3
	MetricType_BOUNCE_RATE           MetricType = 4
	MetricType_COMMENTS              MetricType = 5
	MetricType_REGISTRATIONS         MetricType = 6
	MetricType_PAGE_LOAD_TIME        MetricType = 7
	MetricType_ERROR_RATE            MetricType = 8
	MetricType_SERVER_RESPONSE_TIME  MetricType = 9
	MetricType_STREAMING_PERFORMANCE MetricType = 10
	MetricType_AVG_VIEW_DURATION     MetricType = 11
	MetricType_POPULAR_GENRES        MetricType = 12
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0:  "NEW_USERS",
		1:  "AVG_TIME_ON_SITE",
		3:  "PAGE_VIEWS",
		4:  "BOUNCE_RATE",
		5:  "COMMENTS",
		6:  "REGISTRATIONS",
		7:  "PAGE_LOAD_TIME",
		8:  "ERROR_RATE",
		9:  "SERVER_RESPONSE_TIME",
		10: "STREAMING_PERFORMANCE",
		11: "AVG_VIEW_DURATION",
		12: "POPULAR_GENRES",
	}
	MetricType_value = map[string]int32{
		"NEW_USERS":             0,
		"AVG_TIME_ON_SITE":      1,
		"PAGE_VIEWS":            3,
		"BOUNCE_RATE":           4,
		"COMMENTS":              5,
		"REGISTRATIONS":         6,
		"PAGE_LOAD_TIME":        7,
		"ERROR_RATE":            8,
		"SERVER_RESPONSE_TIME":  9,
		"STREAMING_PERFORMANCE": 10,
		"AVG_VIEW_DURATION":     11,
		"POPULAR_GENRES":        12,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_metrics_v1_metrics_v1_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_protos_metrics_v1_metrics_v1_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_protos_metrics_v1_metrics_v1_proto_rawDescGZIP(), []int{0}
}

type NewUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewUserRequest) Reset() {
	*x = NewUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metrics_v1_metrics_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRequest) ProtoMessage() {}

func (x *NewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metrics_v1_metrics_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRequest.ProtoReflect.Descriptor instead.
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_metrics_v1_metrics_v1_proto_rawDescGZIP(), []int{0}
}

type AvgTimeOnSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *AvgTimeOnSiteRequest) Reset() {
	*x = AvgTimeOnSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metrics_v1_metrics_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgTimeOnSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgTimeOnSiteRequest) ProtoMessage() {}

func (x *AvgTimeOnSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metrics_v1_metrics_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgTimeOnSiteRequest.ProtoReflect.Descriptor instead.
func (*AvgTimeOnSiteRequest) Descriptor() ([]byte, []int) {
	return file_protos_metrics_v1_metrics_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AvgTimeOnSiteRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type MetricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metrics_v1_metrics_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metrics_v1_metrics_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_protos_metrics_v1_metrics_v1_proto_rawDescGZIP(), []int{2}
}

var File_protos_metrics_v1_metrics_v1_proto protoreflect.FileDescriptor

var file_protos_metrics_v1_metrics_v1_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x5f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x76, 0x31,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x41, 0x76, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x6e,
	0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0xf7, 0x01,
	0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x45, 0x57, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x53, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x41,
	0x56, 0x47, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4f, 0x4e, 0x5f, 0x53, 0x49, 0x54, 0x45, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x53, 0x10,
	0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x41, 0x54, 0x45,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x53, 0x10, 0x05,
	0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x53, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x4c, 0x4f, 0x41, 0x44,
	0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x52, 0x41, 0x54, 0x45, 0x10, 0x08, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10,
	0x09, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x50,
	0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x0a, 0x12, 0x15, 0x0a, 0x11,
	0x41, 0x56, 0x47, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x0b, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4f, 0x50, 0x55, 0x4c, 0x41, 0x52, 0x5f, 0x47,
	0x45, 0x4e, 0x52, 0x45, 0x53, 0x10, 0x0c, 0x32, 0x9d, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x56, 0x31, 0x12, 0x41, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4e, 0x65,
	0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0d, 0x41, 0x76, 0x67, 0x54,
	0x69, 0x6d, 0x65, 0x4f, 0x6e, 0x53, 0x69, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x76, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x6e,
	0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_metrics_v1_metrics_v1_proto_rawDescOnce sync.Once
	file_protos_metrics_v1_metrics_v1_proto_rawDescData = file_protos_metrics_v1_metrics_v1_proto_rawDesc
)

func file_protos_metrics_v1_metrics_v1_proto_rawDescGZIP() []byte {
	file_protos_metrics_v1_metrics_v1_proto_rawDescOnce.Do(func() {
		file_protos_metrics_v1_metrics_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_metrics_v1_metrics_v1_proto_rawDescData)
	})
	return file_protos_metrics_v1_metrics_v1_proto_rawDescData
}

var file_protos_metrics_v1_metrics_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_metrics_v1_metrics_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_metrics_v1_metrics_v1_proto_goTypes = []interface{}{
	(MetricType)(0),               // 0: metrics_v1.MetricType
	(*NewUserRequest)(nil),        // 1: metrics_v1.NewUserRequest
	(*AvgTimeOnSiteRequest)(nil),  // 2: metrics_v1.AvgTimeOnSiteRequest
	(*MetricResponse)(nil),        // 3: metrics_v1.MetricResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_protos_metrics_v1_metrics_v1_proto_depIdxs = []int32{
	4, // 0: metrics_v1.AvgTimeOnSiteRequest.time:type_name -> google.protobuf.Timestamp
	1, // 1: metrics_v1.MetricsV1.NewUser:input_type -> metrics_v1.NewUserRequest
	2, // 2: metrics_v1.MetricsV1.AvgTimeOnSite:input_type -> metrics_v1.AvgTimeOnSiteRequest
	3, // 3: metrics_v1.MetricsV1.NewUser:output_type -> metrics_v1.MetricResponse
	3, // 4: metrics_v1.MetricsV1.AvgTimeOnSite:output_type -> metrics_v1.MetricResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_metrics_v1_metrics_v1_proto_init() }
func file_protos_metrics_v1_metrics_v1_proto_init() {
	if File_protos_metrics_v1_metrics_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_metrics_v1_metrics_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metrics_v1_metrics_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgTimeOnSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metrics_v1_metrics_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_metrics_v1_metrics_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_metrics_v1_metrics_v1_proto_goTypes,
		DependencyIndexes: file_protos_metrics_v1_metrics_v1_proto_depIdxs,
		EnumInfos:         file_protos_metrics_v1_metrics_v1_proto_enumTypes,
		MessageInfos:      file_protos_metrics_v1_metrics_v1_proto_msgTypes,
	}.Build()
	File_protos_metrics_v1_metrics_v1_proto = out.File
	file_protos_metrics_v1_metrics_v1_proto_rawDesc = nil
	file_protos_metrics_v1_metrics_v1_proto_goTypes = nil
	file_protos_metrics_v1_metrics_v1_proto_depIdxs = nil
}
